baseurl                 = "https://www.granitz.ml/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "stephan granitz"
theme                   = "hugo-theme-sam"
pygmentsStyle           = "monokai" # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "start"
    galleryFolder       = "images/" # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true # Allow links to the full size images
    smallPreviewImages  = true 
    
    # Show small images from the subfolder instead of the big versions in the gallery
    # Note: This will only become active if clickablePhotos is also true.
    
    smallImagesSubfolder = "small/"
    # The subfolder for the small versions of the images under the gallery (with trailing slash)
    # For each image the small version has to have the same filename as the big version.
    
    footerText          = "Tolstoy: 'The most important knowledge is that which guides the way you lead your life.'"

    description         = "notes on math, statistics, and ai" # max 160 char
    twitterCard         = "summary_large_image"
    # Card value “summary”, “summary_large_image”, “app”, or “player”
    
    primaryImage        = "tn.png"
    # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "notes on math, statistics, and ai"

[[params.mainMenu]]
    link = "/books"
    text = "recent books"

[[params.mainMenu]]
    link = "/about"
    text = "about stephan granitz"
